name: batteries test build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: doc-gen test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install elan and build doc-gen4
        uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail"

      - run: |
         export LEAN_ABORT_ON_PANIC=1
         lake build DocGen4:docs
