name: std4 test build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: std4 test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Checkout and compile batteries
        run: |
          cd ../
          git clone https://github.com/leanprover-community/batteries
          cd batteries
          lake build

      - name: generate docs
        run: |
          cd ../
          ./doc-gen4/test_docs.sh "batteries" "doc-gen4"
